/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Address, ReferenceType } from "./shared";

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice
 */
export interface Invoice {
  Id: string,
  Line: Line[],
  CustomerRef: ReferenceType,
  SyncToken: string,
  DocNumber?: string,
  BillEmail: {
    Address: string
  },
  TxnDate?: Date,
  PrintStatus?: string,
  SalesTermRef?: ReferenceType,
  LinkedTxn?: LinkedTxn[],
  AllowOnlineACHPayment?: boolean,
  DueDate?: string,
  MetaData?: {
    CreateTime: string,
    LastUpdatedTime: string
  },
  BillEmailCc?: {
    Address: string
  },
  CustomerMemo?: {
    value: string
  },
  EmailStatus?: string,
  ProjectRef?: ReferenceType,
  Deposit?: number,
  TxnTaxDetail?: {
    TxnTaxCodeRef: ReferenceType,
    TotalTax: number,
    TaxLine: TaxLine[]
  },
  AllowOnlineCreditCardPayment?: boolean,
  CustomField: CustomField[],
  ShipAddr?: Address,
  BillAddr?: Address,
  ApplyTaxAfterDiscount: boolean,
  TotalAmt: number,
  Balance: number,
  domain?: string,
  sparse?: boolean
}

export interface Line {
  Id: string,
  Description?: string,
  DetailType: string,
  SalesItemLineDetail: {
    TaxCodeRef: ReferenceType,
    Qty: number,
    UnitPrice: number,
    ItemRef: ReferenceType
  },
  LineNum: number,
  Amount: number
}

export interface LinkedTxn {
  TxnId: string,
  TxnType: string  
}

export interface TaxLine {
  DetailType: string,
  Amount: number,
  TaxLineDetail: {
    NetAmountTaxable: number,
    TaxPercent: number,
    TaxRateRef: ReferenceType,
    PercentBased: boolean
  }
}

export interface CustomField {
  DefinitionId: string,
  StringValue: string,
  Type: string,
  Name: string
}
